### ISSUE TITLE
Pay Transaction Fees with Different Inputs

### ISSUE THREAD

**Issue by raspi0124** [monaparty/counterparty-lib#5]
I'm using an account system on coind, and since coind's account system doesn't keep balance in each address, but put multiple account's balance on one address, when I try to send token from the account's address (this address doesn't have any BTC in it since it automatically moved to other address by coind's account system), the api server returned me following:
"Error composing send transaction via API: Insufficient MONA at address XXXXXXXXXXXXXXX. (Need approximately 0.001546 MONA.) To spend unconfirmed coins, use the flag --unconfirmed. (Unconfirmedcoins cannot be spent from multi\u2010sig addresses.)"

To breathly explain, I want to something like explained below.
"A" sends token to "C", and "A" will not pay for traTo breathly explain, I want to something like explained below.
"A" sends token to "C", and "A" will not pay for transaction fee but the other address "B" will pay the transaction fee.
I own both "A" address and "B" address.nsaction fee but the other address "B" will pay the transaction fee.

I own both "A" address and "B" address.

I know this is such a ridiculous to ask this in Issue, but I thought it would be nice to share the solutions.

日本語訳:
Coindに付属しているアカウントシステムを利用しているのですが、どうやらcoindのアカウントシステムは残高をいくつかの貯蔵用アドレスに保管してしまうらしく、貯蔵アドレスではないアドレス(残高は0mona)からトークンをtipしようとするとAPIが"Error composing send transaction via API: Insufficient MONA at address XXXXXXXXXXXXXXX. (Need approximately 0.001546 MONA.) To spend unconfirmed coins, use the flag --unconfirmed. (Unconfirmedcoins cannot be spent from multi\u2010sig addresses.)"と返してきます。これに対応するために以下のようなことをしたいのですが現状可能なのでしょうか?
「AがトークンだけをBに送りトランザクション手数料はCが負担。」
かなりのお手数をおかけすることになりそうですができましたらよろしくお願いします。。

**Comment by raspi0124** [comment]
これ、decoderawtransactionして出た結果を編集してやればいけないこともない気がしてきたので朝やってみます。

**Comment by cryptcoin-junkey** [comment]
This  may help you -> https://github.com/CounterpartyXCP/counterparty-lib/issues/1039#issuecomment-409312475

**Comment by raspi0124** [comment]
OK, First, sorry for quite late response.But It took me quite long to understand.but I finally concluded that none of the way won't work with my enviroment..unfortunately,and since I have no idea of way to manually make counterparty's tx, Im considering to try electrum api instead of coind's account system for supporting monaparty.
Thanks for your support!
When you start to get feeling better, I hope to see you again in somepoint! But now, I hope you will be able have some rest.
Once again, thanks very much for your kindness!
